
era5_varlabels = {
    'tp': r'precipitation [$mm \; day^{-1}$]',
    'msl': r'sea level pressure [$hPa$]',
    'sst': r'SST [$°C$]',
    'hcc': r'high cloud cover [$\%$]',
    'mcc': r'middle cloud cover [$\%$]',
    'lcc': r'low cloud cover [$\%$]',
    'tcc': r'total cloud cover [$\%$]',
    'clear': r'clear sky [$\%$]',
    't2m': r'2 $m$ temperature [$°C$]',
    'msnlwrf': r'surface net LW radiation [$W \; m^{-2}$]',
    'msnswrf': r'surface net SW radiation [$W \; m^{-2}$]',
    'mtdwswrf': r'TOA downward SW radiation [$W \; m^{-2}$]',
    'mtnlwrf': r'TOA net LW radiation [$W \; m^{-2}$]',
    'mtnswrf': r'TOA net SW radiation [$W \; m^{-2}$]',
    'msdwlwrf': r'surface downward LW radiation [$W \; m^{-2}$]',
    'msdwswrf': r'surface downward SW radiation [$W \; m^{-2}$]',
    'msdwlwrfcs': r'clear-sky surface downward LW radiation [$W \; m^{-2}$]',
    'msdwswrfcs': r'clear-sky surface downward SW radiation [$W \; m^{-2}$]',
    'msnlwrfcs': r'clear-sky surface net LW radiation [$W \; m^{-2}$]',
    'msnswrfcs': r'clear-sky surface net SW radiation [$W \; m^{-2}$]',
    'mtnlwrfcs': r'clear-sky TOA net LW radiation [$W \; m^{-2}$]',
    'mtnswrfcs': r'clear-sky TOA net SW radiation [$W \; m^{-2}$]',
    'cbh': r'cloud base height [$m$]',
    'tciw': r'total column cloud ice water [$kg \; m^{-2}$]',
    'tclw': r'total column cloud liquid water [$kg \; m^{-2}$]',
    'e': r'evaporation [$mm \; day^{-1}$]',
    # 'z': r'orography [$m$]',
    'mslhf': r'surface latent heat flux [$W \; m^{-2}$]',
    'msshf': r'surface sensible heat flux [$W \; m^{-2}$]',
    'tcw': r'total column water [$kg \; m^{-2}$]',
    'tcwv': r'total column water vapour [$kg \; m^{-2}$]',
    'tcsw': r'total column snow water [$kg \; m^{-2}$]',
    'tcrw': r'total column rain water [$kg \; m^{-2}$]',
    'tcslw': r'total column supercooled liquid water [$kg \; m^{-2}$]',
    'si10': r'10 $m$ wind speed [$m\;s^{-1}$]',
    'd2m': r'2 $m$ dew temperature [$°C$]',
    'cp': r'convective precipitation [$mm \; day^{-1}$]',
    'lsp': r'large-scale precipitation [$mm \; day^{-1}$]',
    'deg0l': r'0$°C$ isothermal level [$m$]',
    'mper': r'potential evaporation [$mm \; day^{-1}$]',
    'pev': r'potential evaporation [$mm \; day^{-1}$]',
    'skt': r'skin temperature [$°C$]',
    'u10': r'10 $m$ eastward wind speed [$m\;s^{-1}$]',
    'v10': r'10 $m$ northward wind speed [$m\;s^{-1}$]',
    'u100': r'100 $m$ eastward wind speed [$m\;s^{-1}$]',
    'v100': r'100 $m$ northward wind speed [$m\;s^{-1}$]',
    'msuwlwrf': r'surface upward LW radiation [$W \; m^{-2}$]',
    'msuwswrf': r'surface upward SW radiation [$W \; m^{-2}$]',
    'msuwlwrfcs': r'clear-sky surface upward LW radiation [$W \; m^{-2}$]',
    'msuwswrfcs': r'clear-sky surface upward SW radiation [$W \; m^{-2}$]',
    'msnlwrfcl': r'CRE on surface net LW radiation [$W \; m^{-2}$]',
    'msnswrfcl': r'CRE on surface net SW radiation [$W \; m^{-2}$]',
    'msdwlwrfcl': r'CRE on surface downward LW radiation [$W \; m^{-2}$]',
    'msdwswrfcl': r'CRE on surface downward SW radiation [$W \; m^{-2}$]',
    'msuwlwrfcl': r'CRE on surface upward LW radiation [$W \; m^{-2}$]',
    'msuwswrfcl': r'CRE on surface upward SW radiation [$W \; m^{-2}$]',
    'mtuwswrf': r'TOA upward SW radiation [$W \; m^{-2}$]',
    'mtuwswrfcs': r'clear-sky TOA upward SW radiation [$W \; m^{-2}$]',
    'mtnlwrfcl': r'CRE on TOA net LW radiation [$W \; m^{-2}$]',
    'mtnswrfcl': r'CRE on TOA net SW radiation [$W \; m^{-2}$]',
    'mtuwswrfcl': r'CRE on TOA upward SW radiation [$W \; m^{-2}$]',
    'toa_albedo': r'TOA albedo [$-$]',
    'toa_albedocs': r'clear-sky TOA albedo [$-$]',
    'toa_albedocl': r'CRE on TOA albedo [$-$]',
    'msnrf': r'surface net radiation [$W \; m^{-2}$]',
    'q': r'specific humidity [$g \; kg^{-1}$]',
    'pv': r'potential vorticity [$10^{-6} \; K \; m^{2} \; kg^{-1} \; s^{-1}$]',
    'r': r'relative humidity [$\%$]',
    't': r'temperature [$°C$]',
    'u': r'u [$m\;s^{-1}$]',
    'v': r'v [$m\;s^{-1}$]',
    'w': r'w [$Pa\;s^{-1}$]',
    'z': r'geopotential height [$m$]',
    'q2m': r'2 $m$ specific humidity [$g \; kg^{-1}$]',
    'rh2m': r'2 $m$ relative humidity [$\%$]',
    'S': r'$S$ [-]',
    'D': r'$D$ [-]',
    'S+D': r'$S+D$ [-]',
}

cmip6_era5_var = {
    'pr': 'tp',
    'clh': 'hcc',
    'clm': 'mcc',
    'cll': 'lcc',
    'clt': 'tcc',
    'evspsbl': 'e',
    'hfls': 'mslhf',
    'hfss': 'msshf',
    'psl': 'msl',
    'rlds': 'msdwlwrf',
    'rldscs': 'msdwlwrfcs',
    'rlus': 'msuwlwrf',
    'rluscs': 'msuwlwrfcs',
    'rlut': 'mtnlwrf',
    'rlutcs': 'mtnlwrfcs',
    'rsds': 'msdwswrf',
    'rsdscs': 'msdwswrfcs',
    'rsdt': 'mtdwswrf',
    'rsus': 'msuwswrf',
    'rsuscs': 'msuwswrfcs',
    'rsut': 'mtuwswrf',
    'rsutcs': 'mtuwswrfcs',
    'sfcWind': 'si10',
    'tas': 't2m',
    'tos': 'sst',
    'sst': 'sst',
    'ts': 'skt',
    'evspsblpot': 'pev',
    'hurs': 'rh2m',
    'huss': 'q2m',
    'uas': 'u10',
    'vas': 'v10',
    'rlns': 'msnlwrf',
    'rsns': 'msnswrf',
    'rlnscs': 'msnlwrfcs',
    'rsnscs': 'msnswrfcs',
    'rlnscl': 'msnlwrfcl',
    'rsnscl': 'msnswrfcl',
    'rldscl': 'msdwlwrfcl',
    'rsdscl': 'msdwswrfcl',
    'rluscl': 'msuwlwrfcl',
    'rsuscl': 'msuwswrfcl',
    'rsnt': 'mtnswrf',
    'rsntcs': 'mtnswrfcs',
    'rlutcl': 'mtnlwrfcl',
    'rsntcl': 'mtnswrfcl',
    'rsutcl': 'mtuwswrfcl',
    'clwvi': 'tclw',
    'clivi': 'tciw',
    'prw': 'tcwv',
    'rns': 'msnrf',
    'hus': 'q',
    'ta': 't',
    'ua': 'u',
    'va': 'v',
    'wap': 'w',
    'zg': 'z',
    # 'wa',
}

